[package]
name = "winstonallo-kernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "winstonallo-kernel"
test = false
bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9"
