name: rustfmt
on:
    push:
        branches: ["*"]
        paths:
            - src/**
            - tests/**
            - Cargo.toml
            - Cargo.lock
            - .github/workflows/rustfmt.yml
jobs:
    run-rustfmt:
        runs-on: ubuntu-latest
        container: ghcr.io/winstonallo/kernel-test-runner

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Run clippy
              run: cargo fmt -- --check
