name: Integration Tests
on:
    push:
        branches: ["*"]
        paths:
            - src/**
            - tests/**
            - Cargo.toml
            - Cargo.lock
            - .github/workflows/rustfmt.yml
jobs:
    run-cargo-test:
        runs-on: ubuntu-latest
        container: ghcr.io/winstonallo/kernel-test-runner

        strategy:
            matrix:
                toolchain:
                    - nightly
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install clippy
              run: rustup component add rustfmt

            - name: Run clippy
              run: cargo clippy -- --check
