name: Integration Tests
on:
    push:
        branches: ["*"]
jobs:
    run-cargo-test:
        runs-on: ubuntu-latest
        container: image:ghcr.io/winstonallo/kernel-test-runner

        strategy:
            matrix:
                toolchain:
                    - nightly
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run tests
              run: cargo test --test '*'
