name: Integration Tests
on: [push]
jobs:
    run-cargo-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Update package list
              run: sudo apt update

            - name: Install QEMU
              run: sudo apt install -y qemu-system-x86-64

            - name: Run tests
              run: cargo test
